Add category
NSS-Day-Cohort-53/tabloid-full-stack-always-puffy-impalas pull request #54
Opened 2022-04-19 20:06 UTC by SaraHackle

#### Changes Made
1. Added file `CategoryForm.js` to `Components` folder within `client` directory.
2. Modified file `ApplicationViews.js` to include `route`  to `categories/add` that calls the new `CategoryForm`
3. Modified `CategoryList.js` to include Link to `CategoryForm` to allow user to add a new category.
4. Modified `categoryManager.js` to include `addCategory` function, which uses token to verify authorization and performs the POST method. 
​
#### Steps to Review
1. Checkout this branch locally.
    ```
    git fetch --all
    git checkout SH-AddCategory
    ```
2. Open a new Terminal tab (⌘T) and navigate to the server directory.
5. Test app functionality.
    >While a user is viewing the categories list, they can now click the link to add a new category. A form should appear and a new category can now be included in the list. 

6. View code file.
    > Confirm file modifications are present as indicated above.
    > Confirm no unused code or extraneous comments exist.

2022-04-19 20:45 UTC, cjgochanour approved these changes
👍

2022-04-20 14:59 UTC, joshdbarton requested changes

2022-04-20 14:59 UTC, joshdbarton commented on Tabloid/client/src/components/CategoryForm.js
> +    name: "",
Is there anything preventing you from submitting an empty string here?

2022-04-20 15:30 UTC, SaraHackle commented on Tabloid/client/src/components/CategoryForm.js
> +    name: "",
button is now disabled when null.

2022-04-20 16:07 UTC, joshdbarton approved these changes

2022-04-20 16:08 UTC, merged